animations {
    enabled = yes

    # Гладкие горизонтальные анимации окон
    animation = windows, 1, 5, default, slide
    animation = windowsIn, 1, 5, default, slide
    animation = windowsOut, 1, 5, default, slide

    # Горизонтальное переключение рабочих столов
    animation = workspaces, 1, 5, default, slide
    animation = specialWorkspace, 1, 5, default, slide
}
