monitor=,preferred,auto,auto

exec = "~/.config/primeshell/"
env = WLR_DRM_NO_ATOMIC,1          # Решает артефакты при скроллинге
env = WLR_RENDERER_ALLOW_SOFTWARE,0 # Запрещает софтверный рендеринг
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/animations.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/decoration.conf
source = ~/.config/hypr/device.conf
source = ~/.config/hypr/dwindle_layout.conf
source = ~/.config/hypr/environment-variables.conf
source = ~/.config/hypr/general.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/master_layout.conf
source = ~/.config/hypr/misc.conf