input {
    kb_layout = us, ru # There add you language(optional)
    kb_variant =
    kb_model =
    kb_options = grp:win_space_toggle # There you can change keybind, for changing language
    kb_rules =

    follow_mouse = 1

    sensitivity = 0

    touchpad {
        natural_scroll = false
    }
}
