windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0


windowrule = noblur, class:kando
windowrule = opaque, class:kando
windowrule = size 100% 100%, class:kando
windowrule = noborder, class:kando
windowrule = noanim, class:kando
windowrule = float, class:kando
windowrule = pin, class:kando

# Uncomment line 16, if you use kando(this is line from a my first hyprland config > - < )
# bind = ALT, Space, global, kando:example-menu

windowrulev2 = opacity 0.95 0.95, class:^(waybar)$
windowrulev2 = float, title:^otter-launcher$
windowrulev2 = size 800 600, title:^otter-launcher$
windowrulev2 = move center, title:^otter-launcher$
windowrulev2 = stayfocused, class:^(jetbrains-pycharm-ce)$
windowrulev2 = nofocus, class:^(jetbrains-pycharm)$, window_type:^(dialog)$
windowrulev2 = noinitialfocus, class:^(jetbrains-.+)$, floating:1
windowrulev2 = noinitialfocus, class:^(jetbrains-.+)$, floating:1